export {default as Body} from './body/Body'
export {default as Header} from './header/Header'
export {default as Page2Header} from './page2Header/Page2Header'
export {default as Page2Body} from './page2Body/Page2Body'
export {default as Page2Footer} from './page2Footer/Page2Footer'
export {default as Page3Header} from './page3Header/Page3Header'
export {default as Page3Body} from './page3Body/Page3Body'
export {default as Page3Footer} from './page3Footer/Page3Footer'