export {default as Page2Link} from './page2Link/Page2Link'
export {default as Page3Link} from './page3Link/Page3Link'
export {default as WhatsUp} from './whatsUp/WhatsUp'
export {default as Wara} from './wara/Wara'
export {default as Page2BodyTable} from './page2BodyTable/Page2BodyTable'
export {default as HomeLink} from './homeLink/HomeLink'